version: '3.8'

services:
  api:
    container_name: gb-admin-api

    build:
      context: .
      dockerfile: docker/app/Dockerfile

    restart: unless-stopped

    env_file:
      - .env

    ports:
      - ${EXTERNAL_PORT}:8000

    depends_on:
      - postgres
      - redis

  postgres:
    container_name: gb-admin-postgres

    build:
      context: .
      dockerfile: docker/postgres/Dockerfile

    env_file:
      - .env

    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}

    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ${POSTGRES_DATA_VOLUME}:/var/lib/postgresql/data/pgdata

  redis:
    container_name: gb-admin-redis

    image: redis:latest

    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}

    ports:
      - "6377:6379"
